### ISSUE TITLE
[RFC] Introduce new scheme of extension related predefined macro

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-c-api-doc#12]
In https://github.com/riscv/riscv-c-api-doc/pull/10, we've discussed about all future extension-related predefined macro will named with new rule:  `__riscv_<extname>`, e.g. `__riscv_zfh` for `zfh` extension and `__riscv_v` for vector extension.

I think maybe we could also introduce the version info into the marco define, e.g. value of marco is major version * 10000 + minor version * 100 + revise number, so `__riscv_f` is defined as `200200` for f2p2 and `__riscv_b` is defined as `9200` for b0p92

The motivation of this scheme is we have no way to get the current version of each extension.

**Comment by lenary** [comment]
I agree some kind of versioning is sensible, but I'm not sure how that interacts with the main spec moving to a date-based versioning scheme. Are the dates expected to be canonical, or will there also be version numbers always?

**Comment by kito-cheng** [comment]
My understanding is sub-extension will always using major.minor-based versioning scheme and version of main spec meaning a set of default version for each extension.

e.g.
isa-spec-version 2.1 = { I 2.0, E 1.9, M 2.0, A 2.0, F 2.0, D 2.0, Q 2.0, C 2.0}
isa-spec-version 20190608 =  { I 2.1, E 1.9, M 2.0, A 2.0, Zicsr 2.0, Zifencei 2.0, F 2.2, D 2.2, Q 2.2, C 2.0}

So I think extension will always version numbers scheme and won't change in future.
@aswaterman Do you mind confirm my understanding is correct. 

Speaking of ISA spec version, I was consider to add macro for the ISA spec version, but I realize it might not meaningful when user specify -misa-version=20190608 + -march=rv32i2p0; -misa-version=20190608 mean default version for I is 2.1 but -march override that, so the -misa-version become meaningless, and I think the user might care about version for each extension rather than the ISA version.

**Comment by lenary** [comment]
I'm happy for this scheme if we know extensions are always major.minor.revision 

Do we think we need more "space" for minor version numbers, given B is already at 0.92 (though I realise on ratification that will become 1.0, and there shouldn't be too many sets of changes before then). 

I agree that a macro for the isa spec version is potentially confusing given you can override extension versions. Let's just do this for extensions right now.

**Comment by kito-cheng** [comment]
PR created https://github.com/riscv/riscv-c-api-doc/pull/13, so I close this issue :)
